replicaCount: 1

image:
  repository: tahakhadraoui/next-frontend
  tag: 28
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  NEXT_PUBLIC_API_URL: "https://backend.3.208.59.96.sslip.io" 
