replicaCount: 1

image:
  repository: tahakhadraoui/next-frontend
  tag: 32
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  NEXT_PUBLIC_API_URL: "http://a8fef74e3c5774262996ac6cebd4537f-127422608.us-east-1.elb.amazonaws.com"  # utiliser le DNS interne de Kubernetes
