apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: footup-backend-ingress
  namespace: my-namespace
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - backend.44.208.50.112.nip.io
      secretName: footup-backend-tls
  rules:
    - host: backend.44.208.50.112.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
