apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-db-secret
type: Opaque
stringData:
  DB_USERNAME: "{{ .Values.secrets.DB_USERNAME }}"
  DB_PASSWORD: "{{ .Values.secrets.DB_PASSWORD }}"
  