apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-db-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD }}
